POST http://localhost:8080/attach/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="nature.jpg"

< C:\Users\MSI\Desktop\nature.jpg

### Get image
GET http://localhost:8080/attach/open/6df3ccb2-5efd-4c9b-9615-ec98fc898e40.jpg
