### Registration
POST http://localhost:8080/auth/registration
Content-Type: application/json

{
  "name": "Ali",
  "surname": "Aliyev",
  "email": "dkuyliyev@gmail.com",
  "password": "12345",
  "photoId": "31ffc181-5eba-4b5d-9e8c-601881469e18.jpg"
}

### Login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "muham6597@gmail.com",
  "password": "12345"
}

### Resend current email
GET http://localhost:8080/auth/registration/resend/email/dkuyliyev@gmail.com
Content-Type: application/json