

### Create Playlist
POST http://localhost:8080/playlist/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjA3MDI0ODIsImlkIjoiMWJhNGY0ZGUtNWIzYS00NjU1LTgyYzctYWExYWRkZTcyMDQwIiwiZW1haWwiOiJka3V5bGl5ZXZAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3MjA3ODg4ODIsImlzcyI6IllvdXR1YmUifQ.wAD_Dww8la2QshFsp5Cyn1zzBswHqiJdZsQSxYJDeohvNbPN83l4TxaCgOCiDCSrMp3BmsTGKQwUn6pYSLFiTQ

{
  "channelId": "fafa5f3d-e3d8-4cfd-9f35-7995668a4578",
  "name": "Java",
  "description": "Dasturlash tili",
  "orderNum": 1,
  "status": "PUBLIC"
}

###
GET http://localhost:8080/playlist/adm/1ba4f4de-5b3a-4655-82c7-aa1adde72040
Content-Type: application/json