
### Create video
POST http://localhost:8080/video/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjA3MDI0ODIsImlkIjoiMWJhNGY0ZGUtNWIzYS00NjU1LTgyYzctYWExYWRkZTcyMDQwIiwiZW1haWwiOiJka3V5bGl5ZXZAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3MjA3ODg4ODIsImlzcyI6IllvdXR1YmUifQ.wAD_Dww8la2QshFsp5Cyn1zzBswHqiJdZsQSxYJDeohvNbPN83l4TxaCgOCiDCSrMp3BmsTGKQwUn6pYSLFiTQ

{
  "title": "Panda",
  "description": "funny pandas dance",
  "previewAttachId": "6df3ccb2-5efd-4c9b-9615-ec98fc898e40.jpg",
  "playlistId": "4cb40dc9-c4b0-431a-97e6-ce1e1ebcaa64",
  "channelId": "fafa5f3d-e3d8-4cfd-9f35-7995668a4578",
  "categoryId": 2,
  "videoId": "89d7116a-5f89-4d5f-aa2c-225846b07c63.mp4",
  "videoType": "VIDEO",
  "tagIds": [
    "2920d79b-a0b3-45d5-90fa-2a0a3cbea353",
    "9322aaca-d0dc-44ec-8454-a4417abb2e5d"
  ]
}